### ISSUE TITLE
no contract when got PR

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#12]

**Comment by anna06test** [comment]
PR is submited, now adding bounty

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 32.00
Contract address: [0x48a6e645b83f63b8871d055ed5ff7a7e719b0894](https://ropsten.etherscan.io/address/0x48a6e645b83f63b8871d055ed5ff7a7e719b0894)
Network: Testnet (Ropsten)
Paid to: annadanchenko

**Comment by anna06test** [comment]
got snt on contract will merge pr
