### ISSUE TITLE
Fix this today!

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#18]
bug description

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 40.00
Contract address: [0x7c90e40e04fc17f83edb676579013c61a77c005f](https://ropsten.etherscan.io/address/0x7c90e40e04fc17f83edb676579013c61a77c005f)
Network: Testnet (Ropsten)
Paid to: annadanchenko
