### ISSUE TITLE
readded

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#5]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 45.00
Contract address: [0x9be82b7ac8c12cb481de16bfb5b98a9fee07174f](https://ropsten.etherscan.io/address/0x9be82b7ac8c12cb481de16bfb5b98a9fee07174f)
Network: Testnet (Ropsten)
Paid to: annadanchenko
