### ISSUE TITLE
test14 close

### ISSUE THREAD

**Issue by anna06test** [Anna06TestORG/ORG1#7]

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 23.00
Contract address: [0xb1f71970ccbd144c70ce4c1ffaaf2bde43c630c3](https://ropsten.etherscan.io/address/0xb1f71970ccbd144c70ce4c1ffaaf2bde43c630c3)
Network: Testnet (Ropsten)
Paid to: annadanchenko
